---
abstract: 'Language Server and Debug Protocol Adapter for Perl'
author:
  - 'grichter <richter@ecos.de>'
build_requires:
  Test::More: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.34, CPAN::Meta::Converter version 2.150010'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Perl-LanguageServer
no_index:
  directory:
    - t
    - inc
requires:
  AnyEvent: '0'
  AnyEvent::AIO: '0'
  Class::Refresh: '0'
  Compiler::Lexer: '0.23'
  Coro: '0'
  Data::Dump: '0'
  IO::AIO: '0'
  JSON: '0'
  Moose: '0'
  PadWalker: '0'
  Scalar::Util: '0'
  perl: '5.014'
resources:
  repository: https://github.com/richterger/Perl-LanguageServer.git
version: v2.3.0
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
